targetDir: dataset
outputDir: .
baseUri: https://mltd.pikopikopla.net/
validation:
  undefinedSubject:
    - url: https://www.w3.org/2002/07/owl
      startswith: http://www.w3.org/2002/07/owl#
      langtype: turtle
  fileEncoding:
    - target: "*"
      charset: utf-8
      end_of_line: lf
      indent_style: space
      insert_final_newline: true
      trim_trailing_whitespace: true
