name: CI(pull request)

on: pull_request

jobs:
  rdflint:
    name: rdflint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: imas/setup-rdflint@v1
    - name: Run rdflint
      run: rdflint
